# Generated by Django 5.2.9 on 2026-01-08 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalorieResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmr", models.FloatField()),
                ("maintenance_calories", models.FloatField()),
                ("target_calories", models.FloatField()),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("loss", "Weight Loss"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Weight Gain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast_calories", models.IntegerField()),
                ("lunch_calories", models.IntegerField()),
                ("dinner_calories", models.IntegerField()),
                ("snacks_calories", models.IntegerField()),
                ("guidelines", models.TextField()),
                (
                    "calorie_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plan",
                        to="CalorieCal.calorieresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Userprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("height_cm", models.FloatField(help_text="Height in centimeters")),
                ("weight_kg", models.FloatField(help_text="Weight in kilograms")),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Lightly Active"),
                            ("moderate", "Moderately Active"),
                            ("active", "Very Active"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("loss", "Weight Loss"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Weight Gain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="calorieresult",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="CalorieCal.userprofile",
            ),
        ),
    ]
