# Generated by Django 5.2.9 on 2026-01-05 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("height_cm", models.FloatField(help_text="Height in centimeters")),
                ("weight_kg", models.FloatField(help_text="Weight in kilograms")),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Lightly Active"),
                            ("moderate", "Moderately Active"),
                            ("active", "Very Active"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("loss", "Weight Loss"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Weight Gain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CalorieResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmr", models.FloatField()),
                ("maintenance_calories", models.FloatField()),
                ("target_calories", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="CalorieCal.userprofile",
                    ),
                ),
            ],
        ),
    ]
