# Generated by Django 5.2.9 on 2026-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalorieCal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="ai_suggestion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
