# Generated by Django 5.2.9 on 2026-01-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalorieCal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calorieresult",
            name="goal",
            field=models.CharField(
                choices=[
                    ("loss", "Weight Loss"),
                    ("maintain", "Maintain Weight"),
                    ("gain", "Weight Gain"),
                ],
                default="maintain",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast_calories", models.IntegerField()),
                ("lunch_calories", models.IntegerField()),
                ("dinner_calories", models.IntegerField()),
                ("snacks_calories", models.IntegerField()),
                ("guidelines", models.TextField()),
                (
                    "calorie_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plan",
                        to="CalorieCal.calorieresult",
                    ),
                ),
            ],
        ),
    ]
